package com.boot.dbskins.Model;
public enum NameOfSkins {
    LOTOS, DRAGON, REDLINE, FOBOS, LUCKY, WINSTON, TESS, FLASH, POWER, IMPERIAL, GALAXY, RED, LEGION, GIGABYTE,
    DARK, MAGNESUIM, MAJOR, CONDIUT, FERRARI, BEAR, CLOSE, HIKARI, MAGNUS, EAC, FACEIT, TORNADO, MELIDOAS, DIPSIZE
}
